plugins/scrum/config/routes.rb
# Plugin's routes
# See: http://guides.rubyonrails.org/routing.html

# Copyright © Emilio González Montaña
# Licence: Attribution & no derivates
#   * Attribution to the plugin web page URL should be done if you want to use it.
#     https://redmine.ociotec.com/projects/redmine-plugin-scrum
#   * No derivates of this plugin (or partial) are allowed.
# Take a look to licence.txt file at plugin root folder for further details.

resources :projects do
  resources :sprints, :shallow => true do
    member do
      get :edit_effort
      post :update_effort
      get :burndown
      get :burndown_graph
      get :stats
      post :sort
    end
    collection do
      get :burndown_index
      get :stats_index
    end
  end
  post "sprints/change_task_status",
       :controller => :sprints, :action => :change_task_status,
       :as => :sprints_change_task_status

  resources :product_backlog, :shallow => true, :only => [:index] do
    collection do
      post :sort
      post :create_pbi
      get :burndown
      get :burndown_graph
      get :check_dependencies
    end
  end
  get "product_backlog/new_pbi/:tracker_id",
      :controller => :product_backlog, :action => :new_pbi,
      :as => :product_backlog_new_pbi

  get "release_plan",
      :controller => :scrum, :action => :release_plan,
      :as => :release_plan
  get "scrum/stats",
      :controller => :scrum, :action => :stats,
      :as => :scrum_stats

end

post "issues/:id/story_points",
     :controller => :scrum, :action => :change_story_points,
     :as => :change_story_points
post "issues/:id/pending_effort",
     :controller => :scrum, :action => :change_pending_effort,
     :as => :change_pending_effort
post "issues/:id/pending_efforts",
     :controller => :scrum, :action => :change_pending_efforts,
     :as => :change_pending_efforts
post "issues/:id/assigned_to",
     :controller => :scrum, :action => :change_assigned_to,
     :as => :change_assigned_to
get "issues/:id/time_entry",
     :controller => :scrum, :action => :new_time_entry,
     :as => :new_scrum_time_entry
post "issues/:id/time_entry",
     :controller => :scrum, :action => :create_time_entry,
     :as => :create_scrum_time_entry
get "scrum/:sprint_id/new_pbi/:tracker_id",
     :controller => :scrum, :action => :new_pbi,
     :as => :new_pbi
post "scrum/:sprint_id/create_pbi",
     :controller => :scrum, :action => :create_pbi,
     :as => :create_pbi
get "scrum/:pbi_id/new/:tracker_id",
    :controller => :scrum, :action => :new_task,
    :as => :new_task
post "scrum/:pbi_id/create_task",
     :controller => :scrum, :action => :create_task,
     :as => :create_task
get "scrum/:pbi_id/edit_pbi",
    :controller => :scrum, :action => :edit_pbi,
    :as => :edit_pbi
post "scrum/:pbi_id/update_pbi",
     :controller => :scrum, :action => :update_pbi,
     :as => :update_pbi
get "scrum/:pbi_id/move/:position",
    :controller => :scrum, :action => :move_pbi,
    :as => :move_pbi
get "scrum/:id/edit_task",
    :controller => :scrum, :action => :edit_task,
    :as => :edit_task
post "scrum/:id/update_task",
     :controller => :scrum, :action => :update_task,
     :as => :update_task
post "scrum/:pbi_id/move_to_last_sprint",
     :controller => :scrum, :action => :move_to_last_sprint,
     :as => :move_to_last_sprint
post "scrum/:pbi_id/move_to_product_backlog",
     :controller => :scrum, :action => :move_to_product_backlog,
     :as => :move_to_product_backlog

plugins/scrum/app/controllers/scrum_controller.rb
# Copyright © Emilio González Montaña
# Licence: Attribution & no derivates
#   * Attribution to the plugin web page URL should be done if you want to use it.
#     https://redmine.ociotec.com/projects/redmine-plugin-scrum
#   * No derivates of this plugin (or partial) are allowed.
# Take a look to licence.txt file at plugin root folder for further details.

class ScrumController < ApplicationController

  menu_item :product_backlog, :except => [:stats]
  menu_item :overview, :only => [:stats]

  before_filter :find_issue, :only => [:change_story_points, :change_pending_effort, :change_assigned_to,
                                       :new_time_entry, :create_time_entry, :edit_task, :update_task,
                                       :change_pending_efforts]
  before_filter :find_sprint, :only => [:new_pbi, :create_pbi]
  before_filter :find_pbi, :only => [:new_task, :create_task, :edit_pbi, :update_pbi, :move_pbi,
                                     :move_to_last_sprint, :move_to_product_backlog]
  before_filter :find_project_by_project_id, :only => [:release_plan, :stats]
  before_filter :authorize, :except => [:new_pbi, :create_pbi, :new_task, :create_task,
                                        :new_time_entry, :create_time_entry,
                                        :change_pending_efforts]
  before_filter :authorize_add_issues, :only => [:new_pbi, :create_pbi, :new_task, :create_task]
  before_filter :authorize_log_time, :only => [:new_time_entry, :create_time_entry]
  before_filter :authorize_edit_issues, :only => [:change_pending_efforts]

  helper :scrum
  helper :timelog
  helper :custom_fields
  helper :projects

  def change_story_points
    begin
      @issue.story_points = params[:value]
      status = 200
    rescue
      status = 503
    end
    render :nothing => true, :status => status
  end

  def change_pending_effort
    PendingEffort.create(issue_id: @issue.id, date: Time.now, effort: params[:value].to_f)
    render :nothing => true, :status => 200
  end

  def change_pending_efforts
    params['pending_efforts'].each_pair do |id, value|
      pending_effort = PendingEffort.find(id)
      raise "Invalid pending effort ID #{id}" if pending_effort.nil?
      raise "Pending effort ID #{id} is not owned by this issue" if pending_effort.issue_id != @issue.id
      pending_effort.effort = value.to_f
      pending_effort.save!
    end
    redirect_to issue_path(@issue)
  end

  def change_assigned_to
    @issue.init_journal(User.current)
    @issue.assigned_to = params[:value].blank? ? nil : User.find(params[:value].to_i)
    @issue.save!
    render_task(@project, @issue, params)
  end

  def new_time_entry
    @pbi_status_id = params[:pbi_status_id]
    @other_pbi_status_ids = params[:other_pbi_status_ids]
    @task_id = params[:task_id]
    respond_to do |format|
      format.js
    end
  end

  def create_time_entry
    begin
      time_entry_params = params[:time_entry]
      time_entry = TimeEntry.new(time_entry_params.except(:adjust_effort, :pending_efforts))
      time_entry.project_id = @project.id
      time_entry.issue_id = @issue.id
      time_entry.user_id = time_entry_params[:user_id]
      call_hook(:controller_timelog_edit_before_save, {:params => params, :time_entry => time_entry})
      time_entry.save!

      if time_entry_params[:adjust_effort].present?
        is_manual = (time_entry_params[:adjust_effort] == 'manual')
        effort = is_manual ? time_entry_params[:pending_efforts].to_f : @issue.pending_effort.to_f - time_entry_params[:hours].to_f
        if @issue.pending_effort.to_f > 0 || (is_manual && effort > 0)
          PendingEffort.create(issue_id: @issue.id, date: Time.now, effort: effort > 0 ? effort : 0)
        end
      end

    rescue Exception => @exception
      logger.error("Exception: #{@exception.inspect}")
    end
    respond_to do |format|
      format.js
    end
  end

  def new_pbi
    @pbi = Issue.new
    @pbi.project = @project
    @pbi.tracker = @project.trackers.find(params[:tracker_id])
    @pbi.author = User.current
    @pbi.sprint = @sprint
    @top = true unless params[:top].nil? or (params[:top] == "false")
    respond_to do |format|
      format.html
      format.js
    end
  end

  def create_pbi
    begin
      @continue = !(params[:create_and_continue].nil?)
      @top = !(params[:top].nil?)
      @pbi = Issue.new
      @pbi.project = @project
      @pbi.author = User.current
      @pbi.tracker_id = params[:issue][:tracker_id]
      update_attributes(@pbi, params)
      if @top
        @pbi.set_on_top
        @pbi.save!
      end
      @pbi.sprint = @sprint
      @pbi.save!
    rescue Exception => @exception
      logger.error("Exception: #{@exception.inspect}")
    end
    respond_to do |format|
      format.js
    end
  end

  def edit_pbi
    respond_to do |format|
      format.js
    end
  end

  def update_pbi
    begin
      @pbi.init_journal(User.current, params[:issue][:notes])
      update_attributes(@pbi, params)
      @pbi.save!
    rescue Exception => @exception
      logger.error("Exception: #{@exception.inspect}")
    end
    respond_to do |format|
      format.js
    end
  end

  def move_pbi
    begin
      @position = params[:position]
      case params[:position]
        when "top", "bottom"
          @pbi.move_pbi_to(@position)
        when "before"
          @other_pbi = params[:before_other_pbi]
          @pbi.move_pbi_to(@position, @other_pbi)
        when "after"
          @other_pbi = params[:after_other_pbi]
          @pbi.move_pbi_to(@position, @other_pbi)
        else
          raise "Invalid position: #{@position.inspect}"
      end
    rescue Exception => @exception
      logger.error("Exception: #{@exception.inspect}")
    end
  end

  def move_to_last_sprint
    begin
      raise "The project hasn't defined any Sprint yet" unless @project.last_sprint
      @previous_sprint = @pbi.sprint
      move_issue_to_sprint(@pbi, @project.last_sprint)
    rescue Exception => @exception
      logger.error("Exception: #{@exception.inspect}")
    end
    respond_to do |format|
      format.js
    end
  end

  def move_to_product_backlog
    begin
      raise "The project hasn't defined the Product Backlog yet" unless @project.product_backlog
      move_issue_to_sprint(@pbi, @project.product_backlog)
    rescue Exception => @exception
      logger.error("Exception: #{@exception.inspect}")
    end
    respond_to do |format|
      format.js
    end
  end

  def new_task
    @task = Issue.new
    @task.project = @project
    @task.tracker = Tracker.find(params[:tracker_id])
    @task.parent = @pbi
    @task.author = User.current
    @task.sprint = @sprint
    if Scrum::Setting.inherit_pbi_attributes
      @task.inherit_from_issue(@pbi)
    end
    respond_to do |format|
      format.html
      format.js
    end
  rescue Exception => e
    logger.error("Exception: #{e.inspect}")
    render_404
  end

  def create_task
    begin
      @continue = !(params[:create_and_continue].nil?)
      @task = Issue.new
      @task.project = @project
      @task.parent_issue_id = @pbi.id
      @task.author = User.current
      @task.sprint = @sprint
      @task.tracker_id = params[:issue][:tracker_id]
      update_attributes(@task, params)
      @task.save!
      @task.pending_effort = params[:issue][:pending_effort]
    rescue Exception => @exception
    end
    respond_to do |format|
      format.js
    end
  end

  def edit_task
    respond_to do |format|
      format.js
    end
  end

  def update_task
    begin
      @issue.init_journal(User.current, params[:issue][:notes])
      @old_status = @issue.status
      update_attributes(@issue, params)
      @issue.save!
      @issue.pending_effort = params[:issue][:pending_effort]
      unless @issue.parent_id.blank?
        parent = Issue.find_by_id(@issue.parent_id)
        parent_issues_statuses_ids = Issue.all.where(parent_id: parent.id).collect(&:status_id).uniq
        if parent_issues_statuses_ids.size.eql? 1
          if Scrum::Setting.when_all_subtasks_status_id.eql? parent_issues_statuses_ids[0]
            parent.status = IssueStatus.find(Scrum::Setting.user_story_move_status_id)
            parent.save!
          end
        end
      end
    rescue Exception => @exception
      logger.error("Exception: #{@exception.inspect}")
    end
    respond_to do |format|
      format.js
    end
  end

  def release_plan
    @product_backlog = @project.product_backlog
    @sprints = []
    velocity_all_pbis, velocity_scheduled_pbis, @sprints_count = @project.story_points_per_sprint
    @velocity_type = params[:velocity_type] || "only_scheduled"
    case @velocity_type
      when "all"
        @velocity = velocity_all_pbis
      when "only_scheduled"
        @velocity = velocity_scheduled_pbis
      else
        @velocity = params[:custom_velocity].to_f unless params[:custom_velocity].blank?
    end
    @velocity = 1.0 if @velocity.blank? or @velocity < 1.0
    @total_story_points = 0.0
    @pbis_with_estimation = 0
    @pbis_without_estimation = 0
    versions = {}
    accumulated_story_points = @velocity
    current_sprint = {:pbis => [], :story_points => 0.0, :versions => []}
    if @project.product_backlog
      @project.product_backlog.pbis.each do |pbi|
        if pbi.story_points
          @pbis_with_estimation += 1
          story_points = pbi.story_points.to_f
          @total_story_points += story_points
          while accumulated_story_points < story_points
            @sprints << current_sprint
            accumulated_story_points += @velocity
            current_sprint = {:pbis => [], :story_points => 0.0, :versions => []}
          end
          accumulated_story_points -= story_points
          current_sprint[:pbis] << pbi
          current_sprint[:story_points] += story_points
          if pbi.fixed_version
            versions[pbi.fixed_version.id] = {:version => pbi.fixed_version,
                                              :sprint => @sprints.count}

plugins/scrum/app/helpers/scrum_helper.rb
# Copyright © Emilio González Montaña
# Licence: Attribution & no derivates
#   * Attribution to the plugin web page URL should be done if you want to use it.
#     https://redmine.ociotec.com/projects/redmine-plugin-scrum
#   * No derivates of this plugin (or partial) are allowed.
# Take a look to licence.txt file at plugin root folder for further details.

module ScrumHelper

  include ProjectsHelper

  def render_hours(hours, options = {})
    if hours.nil?
      ""
    else
      if hours.is_a?(Integer)
        text = ("%d" % hours) unless options[:ignore_zero] and hours == 0
      elsif hours.is_a?(Float)
        text = ("%g" % hours) unless options[:ignore_zero] and hours == 0.0
      else
        text = hours unless options[:ignore_zero] and (hours.blank? or (hours == "0"))
      end
      unless text.blank?
        text = "#{text}h"
        unless options[:link].nil?
          text = link_to(text, options[:link])
        end
        render :inline => "<span title=\"#{options[:title]}\">#{text}</span>"
      end
    end
  end

  def render_pbi_left_header(pbi)
    parts = []
    if Scrum::Setting.render_position_on_pbi
      parts << "#{l(:field_position)}: #{pbi.position}"
    end
    if Scrum::Setting.render_category_on_pbi and pbi.category
      parts << "#{l(:field_category)}: #{h(pbi.category.name)}"
    end
    if Scrum::Setting.render_version_on_pbi and pbi.fixed_version
      parts << "#{l(:field_fixed_version)}: #{link_to_version(pbi.fixed_version)}"
    end
    render :inline => parts.join(", ")
  end

  def render_pbi_right_header(pbi)
    parts = []
    if Scrum::Setting.render_author_on_pbi
      parts << authoring(pbi.created_on, pbi.author)
    end
    if Scrum::Setting.render_updated_on_pbi and pbi.created_on != pbi.updated_on
      parts << "#{l(:label_updated_time, time_tag(pbi.updated_on))}"
    end
    render :inline => parts.join(", ")
  end

  def render_issue_icons(issue)
    icons = []
    if ((issue.is_pbi? and Scrum::Setting.render_pbis_speed) or
        (issue.is_task? and Scrum::Setting.render_tasks_speed))
      if (speed = issue.speed)
        if speed <= Scrum::Setting.lowest_speed
          icons << render_issue_icon(LOWEST_SPEED_ICON, speed)
        elsif speed <= Scrum::Setting.low_speed
          icons << render_issue_icon(LOW_SPEED_ICON, speed)
        elsif speed >= Scrum::Setting.high_speed
          icons << render_issue_icon(HIGH_SPEED_ICON, speed)
        end
      end
    end
    render :inline => icons.join('\n')
  end

  DEVIATION_ICONS = [LOWEST_SPEED_ICON = "icon-major-deviation",
                     LOW_SPEED_ICON = "icon-minor-deviation",
                     HIGH_SPEED_ICON = "icon-below-deviation"]

private

  def render_issue_icon(icon, speed)
    link_to("", "#", :class => "icon float-icon #{icon}",
            :title => l(:label_issue_speed, :speed => speed))
  end

end

plugins/scrum/app/views/scrum/_create_time_entry.html.erb
<h3 class="title"><%= l(:field_time_entries) %></h3>

<div id="messages"/>
<%= form_for :time_entry, :url => create_scrum_time_entry_path(@issue), :remote => true do |f| %>
    <%= back_url_hidden_field_tag %>
    <%= error_messages_for 'time_entry' %>
    <%= hidden_field_tag :pbi_status_id, @pbi_status_id %>
    <%= hidden_field_tag :other_pbi_status_ids, @other_pbi_status_ids %>
    <%= hidden_field_tag :task_id, @task_id %>
    <div class="box tabular">
      <p>
        <label><%= l(:field_hours) %>:</label>
        <%= f.text_field :hours, :size => 15, :required => true %>
      </p>

      <p>
        <label><%= l(:field_pending_effort) %>:</label>
        <%= f.radio_button 'adjust_effort', 'automatically', checked: Scrum::Setting.adjust_effort_automatically %><%= l(:label_adjust_effort_automatically) %>
        <br>
        <%= f.radio_button 'adjust_effort', 'manual', checked: !Scrum::Setting.adjust_effort_automatically %><%= l(:label_manual_set_effort_to) %>
        <%= f.text_field :pending_efforts, :value => @issue.pending_effort, :size => 3 %>
        <%= l(:field_hours).downcase %>
      </p>

      <p>
        <label><%= l(:field_spent_on) %>:</label>
        <%= f.text_field :spent_on, :size => 10, :value => Date.today, :required => true %>
      </p>

      <p>
        <label><%= l(:field_comments) %>:</label>
        <%= f.text_field :comments, :size => 15, :maxlength => 255 %>
      </p>

      <p>
        <label><%= l(:field_activity) %>:</label>
        <%= f.select :activity_id,
                     @project.activities.collect { |activity| [activity.name, activity.id] },
                     :include_blank => true, :required => true %>
      </p>

      <p>
        <label><%= l(:field_user) %>:</label>
        <%= f.select :user_id,
                     principals_options_for_select(@issue.assignable_users, @issue.assigned_to),
                     :required => true %>
      </p>

      <%- TimeEntry.new.custom_field_values.each do |value| -%>
          <p>
            <label><%= value.custom_field.name %>:</label>
            <%= custom_field_tag :time_entry, value %>
          </p>
      <%- end -%>

      <p>
        <%= submit_tag l(:button_save) %>
      </p>
    </div>
<% end %>

plugins/scrum/app/views/scrum/_edit_pbi_modal.html.erb
<h3 class="title"><%= "#{@pbi.tracker.name} ##{@pbi.id}" %></h3>

<%- there_is_last_sprint = (!(@project.last_sprint.nil?))
    there_is_product_backlog = (!(@project.product_backlog.nil?))
    render_move_to_last_sprint = (there_is_last_sprint and
                                  ((@pbi.sprint.is_product_backlog?) or (@pbi.sprint.id != @project.last_sprint.id)))
    render_move_to_product_backlog = (there_is_product_backlog and (@pbi.sprint.id != @project.product_backlog.id))
    render_move_pbi = (there_is_product_backlog and (@pbi.sprint.id == @project.product_backlog.id) and
                       User.current.allowed_to?(:sort_product_backlog, @project))
    menu_needed = (render_move_to_last_sprint or render_move_to_product_backlog or render_move_pbi) -%>
<%- if menu_needed -%>
  <div class="modal-issue-menu">
    <%- if render_move_pbi -%>
      <%= form_tag(move_pbi_path(@pbi, :before), :method => :get, :remote => true,
                   :id => "move_pbi_before") do %>
        <%= link_to(l(:label_move_pbi_before), "#", :onclick => "$('#move_pbi_before').submit(); return(false);") %>:
        <%= text_field_tag(:before_other_pbi, "", :size => 3) %>
        <%= javascript_tag "observeAutocompleteField('before_other_pbi', '#{escape_javascript auto_complete_issues_path(:project_id => @project, :scope => (Setting.cross_project_issue_relations? ? 'all' : nil))}')" %>
      <% end %>
      <%= form_tag(move_pbi_path(@pbi, :after), :method => :get, :remote => true,
                   :id => "move_pbi_after") do %>
        <%= link_to(l(:label_move_pbi_after), "#", :onclick => "$('#move_pbi_after').submit(); return(false);") %>:
        <%= text_field_tag(:after_other_pbi, "", :size => 3) %>
        <%= javascript_tag "observeAutocompleteField('after_other_pbi', '#{escape_javascript auto_complete_issues_path(:project_id => @project, :scope => (Setting.cross_project_issue_relations? ? 'all' : nil))}')" %>
      <% end %>
    <%- end -%>
    <%- if render_move_to_last_sprint -%>
      <%= link_to(l(:label_move_pbi_to_last_sprint), move_to_last_sprint_path(@pbi),
                  :remote => true, :method => :post, :class => "icon icon-sprint-board") %>
    <%- end -%>
    <%- if render_move_to_product_backlog -%>
      <%= link_to(l(:label_move_pbi_to_product_backlog), move_to_product_backlog_path(@pbi),
                  :remote => true, :method => :post, :class => "icon icon-product-backlog") %>
    <%- end -%>
  </div>
<%- end -%>

<div id="messages" />

<%= labelled_form_for @pbi, :url => update_pbi_path(@pbi), :method => :post, :remote => true do |f| %>
  <%= back_url_hidden_field_tag %>
  <%= f.hidden_field :tracker_id, :value => @pbi.tracker_id %>
  <%= f.hidden_field :sprint_id, :value => @pbi.sprint_id %>
  <%= error_messages_for "pbi" %>
  <%= render :partial => "scrum/edit_issue_attributes", :formats => [:html],
             :locals => {:f => f, :issue => @pbi} %>
<% end %>

plugins/scrum/app/views/scrum/_new_pbi_modal.html.erb
<h3 class="title"><%= @pbi.tracker.name %></h3>

<div id="messages" />

<%= labelled_form_for @pbi, :url => create_pbi_path(@sprint), :remote => true do |f| %>
  <%= back_url_hidden_field_tag %>
  <%= f.hidden_field :tracker_id, :value => @pbi.tracker_id %>
  <%= f.hidden_field :sprint_id, :value => @pbi.sprint_id %>
  <%= hidden_field_tag(:top, true) if @top %>
  <%= error_messages_for "pbi" %>
  <%= render :partial => "scrum/new_issue_attributes", :formats => [:html],
             :locals => {:f => f, :issue => @pbi} %>
<% end %>

plugins/scrum/app/views/scrum/_new_task_modal.html.erb
<h3 class="title"><%= @task.tracker.name %></h3>

<div id="messages" />

<%= labelled_form_for @task, :url => create_task_path(@pbi), :remote => true do |f| %>
  <%= back_url_hidden_field_tag %>
  <%= f.hidden_field :tracker_id, :value => @task.tracker_id %>
  <%= error_messages_for "task" %>
  <%= render :partial => "scrum/new_issue_attributes", :formats => [:html],
             :locals => {:f => f, :issue => @task} %>
<% end %>

plugins/scrum/app/views/scrum/edit_pbi.js.erb
$("#ajax-modal").html("<%= escape_javascript(render :partial => "scrum/edit_pbi_modal") %>");
showModal("ajax-modal", "800px");

plugins/scrum/app/views/scrum/edit_task.js.erb
$("#ajax-modal").html("<%= escape_javascript(render :partial => "scrum/edit_task_modal") %>");
showModal("ajax-modal", "800px");

plugins/scrum/app/views/scrum/new_pbi.js.erb
$("#ajax-modal").html("<%= escape_javascript(render :partial => "scrum/new_pbi_modal") %>");
showModal("ajax-modal", "800px");

plugins/scrum/app/views/scrum/stats.html.erb
<div class="contextual scrum-menu">
  <%= link_to(l(:button_back), project_path(@project), :class => 'icon icon-cancel') %>
</div>

<h2>
  <%= l(:label_scrum_stats) %>
</h2>

<% content_for :header_tags do %>
  <%= javascript_include_tag "d3.#{Rails.env.development? ? '' : 'min.'}js", :plugin => 'scrum' %>
  <%= javascript_include_tag 'xcharts.min.js', :plugin => 'scrum' %>
  <%= javascript_include_tag "nv.d3.#{Rails.env.development? ? '' : 'min.'}js", :plugin => 'scrum' %>
  <%= stylesheet_link_tag 'xcharts.min.css', :plugin => 'scrum' %>
  <%= stylesheet_link_tag "nv.d3.#{Rails.env.development? ? '' : 'min.'}css", :plugin => 'scrum' %>
<% end %>

<h3 align="center">
  <%= l(:label_hours_per_story_point) %>
  (<%= l(:label_sprint_plural) %>)
</h3>
<div id="<%= @hours_per_story_point_chart[:id] %>">
  <svg style="height: <%= @hours_per_story_point_chart[:height] %>px;">
  </svg>
</div>
<%= render :partial => 'common/bar_chart',
           :formats => [:js],
           :locals => {:graph => @hours_per_story_point_chart,
                       :element => {:label => l(:enumeration_activities), :name => :activity},
                       :rows => @hours_per_story_point} %>

<% content_for :sidebar do %>
  <%= render :partial => 'projects/sidebar' %>
<% end %>

<br />
<br />

<h3 align="center">
  <%= l(:label_sps_by_pbi_category) %>
  (<%= l(:label_sprint_plural) %> + <%= l(:label_product_backlog) %>)
</h3>
<%- if @sps_by_pbi_category.count < 1 -%>
    <p class="nodata"><%= l(:label_no_data) %></p>
<%- else -%>
    <%= render :partial => 'common/stat_graph_and_table',
               :locals => {:graph => {:id => 'stats_sps_per_category', :width => 400, :height => 400},
                           :element => {:label => l(:label_issue_category_plural), :name => :category},
                           :unit => {:label => l(:label_story_point_unit), :plural_label => l(:label_story_point_plural)},
                           :rows => @sps_by_pbi_category,
                           :total => @sps_by_pbi_category_total} %>
<%- end -%>

<br />
<br />

<h3 align="center">
  <%= l(:label_sps_by_pbi_type) %>
  (<%= l(:label_sprint_plural) %> + <%= l(:label_product_backlog) %>)
</h3>
<%- if @sps_by_pbi_type.count < 1 -%>
    <p class="nodata"><%= l(:label_no_data) %></p>
<%- else -%>
    <%= render :partial => 'common/stat_graph_and_table',
               :locals => {:graph => {:id => 'stats_sps_per_pbi_type', :width => 400, :height => 400},
                           :element => {:label => l(:label_tracker_plural), :name => :tracker},
                           :unit => {:label => l(:label_story_point_unit), :plural_label => l(:label_story_point_plural)},
                           :rows => @sps_by_pbi_type,
                           :total => @sps_by_pbi_type_total} %>
<%- end -%>

<br />
<br />

<h3 align="center">
  <%= l(:label_time_by_activity) %>
  (<%= l(:label_sprint_plural) %>)
</h3>
<%- if @effort_by_activity.count < 1 -%>
    <p class="nodata"><%= l(:label_no_data) %></p>
<%- else -%>
    <%= render :partial => 'common/stat_graph_and_table',
               :locals => {:graph => {:id => 'stats_time_per_activity', :width => 400, :height => 400},
                           :element => {:label => l(:enumeration_activities), :name => :activity},
                           :unit => {:label => 'h', :plural_label => l(:label_time_entry_plural)},
                           :rows => @effort_by_activity,
                           :total => @effort_by_activity_total} %>
<%- end -%>

<%= render :partial => 'common/scrum_footer' %>