plugins/scrum/config/routes.rb
# Plugin's routes
# See: http://guides.rubyonrails.org/routing.html

# Copyright © Emilio González Montaña
# Licence: Attribution & no derivates
#   * Attribution to the plugin web page URL should be done if you want to use it.
#     https://redmine.ociotec.com/projects/redmine-plugin-scrum
#   * No derivates of this plugin (or partial) are allowed.
# Take a look to licence.txt file at plugin root folder for further details.

resources :projects do
  resources :sprints, :shallow => true do
    member do
      get :edit_effort
      post :update_effort
      get :burndown
      get :burndown_graph
      get :stats
      post :sort
    end
    collection do
      get :burndown_index
      get :stats_index
    end
  end
  post "sprints/change_task_status",
       :controller => :sprints, :action => :change_task_status,
       :as => :sprints_change_task_status

  resources :product_backlog, :shallow => true, :only => [:index] do
    collection do
      post :sort
      post :create_pbi
      get :burndown
      get :burndown_graph
      get :check_dependencies
    end
  end
  get "product_backlog/new_pbi/:tracker_id",
      :controller => :product_backlog, :action => :new_pbi,
      :as => :product_backlog_new_pbi

  get "release_plan",
      :controller => :scrum, :action => :release_plan,
      :as => :release_plan
  get "scrum/stats",
      :controller => :scrum, :action => :stats,
      :as => :scrum_stats

end

post "issues/:id/story_points",
     :controller => :scrum, :action => :change_story_points,
     :as => :change_story_points
post "issues/:id/pending_effort",
     :controller => :scrum, :action => :change_pending_effort,
     :as => :change_pending_effort
post "issues/:id/pending_efforts",
     :controller => :scrum, :action => :change_pending_efforts,
     :as => :change_pending_efforts
post "issues/:id/assigned_to",
     :controller => :scrum, :action => :change_assigned_to,
     :as => :change_assigned_to
get "issues/:id/time_entry",
     :controller => :scrum, :action => :new_time_entry,
     :as => :new_scrum_time_entry
post "issues/:id/time_entry",
     :controller => :scrum, :action => :create_time_entry,
     :as => :create_scrum_time_entry
get "scrum/:sprint_id/new_pbi/:tracker_id",
     :controller => :scrum, :action => :new_pbi,
     :as => :new_pbi
post "scrum/:sprint_id/create_pbi",
     :controller => :scrum, :action => :create_pbi,
     :as => :create_pbi
get "scrum/:pbi_id/new/:tracker_id",
    :controller => :scrum, :action => :new_task,
    :as => :new_task
post "scrum/:pbi_id/create_task",
     :controller => :scrum, :action => :create_task,
     :as => :create_task
get "scrum/:pbi_id/edit_pbi",
    :controller => :scrum, :action => :edit_pbi,
    :as => :edit_pbi
post "scrum/:pbi_id/update_pbi",
     :controller => :scrum, :action => :update_pbi,
     :as => :update_pbi
get "scrum/:pbi_id/move/:position",
    :controller => :scrum, :action => :move_pbi,
    :as => :move_pbi
get "scrum/:id/edit_task",
    :controller => :scrum, :action => :edit_task,
    :as => :edit_task
post "scrum/:id/update_task",
     :controller => :scrum, :action => :update_task,
     :as => :update_task
post "scrum/:pbi_id/move_to_last_sprint",
     :controller => :scrum, :action => :move_to_last_sprint,
     :as => :move_to_last_sprint
post "scrum/:pbi_id/move_to_product_backlog",
     :controller => :scrum, :action => :move_to_product_backlog,
     :as => :move_to_product_backlog

plugins/scrum/app/views/post_its/sprint_board/_custom_fields.html.erb
<%- Scrum::Setting.tracker_fields(issue.tracker.id, Scrum::Setting::TrackerFields::SPRINT_BOARD_CUSTOM_FIELDS).each do |custom_field_id| -%>
    <%- custom_field = CustomField.find(custom_field_id)
        value = issue.custom_value_for(custom_field_id) -%>
    <%- if value.present? and value.value.present? -%>
        <%= content_tag("div", :title => custom_field.description) do %>
            <span class="post-it-legend"><%= custom_field.name %>:</span>
            <%= h(show_value(value)) %>
        <% end %>
    <%- end -%>
<%- end -%>

plugins/scrum/app/views/post_its/sprint_board/_fields.html.erb
<%- if Scrum::Setting.tracker_field?(issue.tracker.id, :status_id, Scrum::Setting::TrackerFields::SPRINT_BOARD_FIELDS) and issue.status -%>
    <%= content_tag("div") do %>
        <span class="post-it-legend"><%= l(:field_status) %>:</span>
        <%= h(issue.status.name) %>
    <% end %>
<%- end -%>

<%- if Scrum::Setting.tracker_field?(issue.tracker.id, :category_id, Scrum::Setting::TrackerFields::SPRINT_BOARD_FIELDS) and issue.category -%>
    <%= content_tag("div") do %>
        <span class="post-it-legend"><%= l(:field_category) %>:</span>
        <%= h(issue.category.name) %>
    <% end %>
<%- end -%>

<%- if Scrum::Setting.tracker_field?(issue.tracker.id, :fixed_version_id, Scrum::Setting::TrackerFields::SPRINT_BOARD_FIELDS) and issue.fixed_version -%>
    <%= content_tag("div") do %>
        <span class="post-it-legend"><%= l(:field_fixed_version) %>:</span>
        <%= link_to_version(issue.fixed_version) %>
    <% end %>
<%- end -%>

plugins/scrum/app/views/post_its/sprint_board/_head.html.erb
<table class="box attributes">
  <tr>
    <td width="300px">
      <div class="tabular">
        <p>
          <label><%= l(:label_sprint) %>:</label>
          <%- options = project.sprints.collect{|other_sprint| [other_sprint.name, path.call(other_sprint)]}
              options = options_for_select(options, path.call(sprint)) -%>
          <%= select_tag "selected_sprint_id", options,
                         :onchange => "if (this.value != '') { window.location = this.value; }" %>
        </p>
        <p>
          <label><%= l(:field_start_date) %>:</label>
          <%= format_date sprint.sprint_start_date %>
        </p>
        <p>
          <label><%= l(:field_end_date) %>:</label>
          <%= format_date sprint.sprint_end_date %>
        </p>
      </div>
    </td>
    <%- if !(sprint.description.blank?) -%>
      <td>
        <%= raw(Redmine::WikiFormatting::Textile::Formatter.new(sprint.description).to_html(true)) %>
      </td>
    <%- end -%>
  </tr>
</table>

plugins/scrum/app/views/post_its/sprint_board/_pbi.html.erb
<%- pbi_id = "pbi_#{pbi.id}" -%>
<table id="<%= pbi_id %>" class="<%= pbi.post_it_css_class(:rotate => true, :scale => true) %>">
  <tr>
    <td class="content" colspan="3">
      <%- if User.current.allowed_to?(:edit_sprint_board, project) and 
             User.current.allowed_to?(:edit_issues, project) and
             pbi.editable? and !read_only -%>
        <%= link_to "", edit_pbi_path(pbi), :remote => true, :method => "GET",
                    :class => "icon icon-edit float-icon", :title => l(:label_edit_pbi) %>
        <%- Tracker.task_trackers.each do |tracker| -%>
          <%= link_to "", new_task_path(pbi, tracker), :remote => true, :method => "GET",
                      :class => "icon icon-add float-icon",
                      :title => l(:label_add_task, :tracker => tracker.name) %>
        <%- end -%>
    <%- end -%>
      <%= render_issue_icons(pbi) %>
      <%= render :partial => "post_its/sprint_board/fields", :formats => [:html],
                 :locals => {:project => project, :issue => pbi} %>
      <div>
        <%= link_to_issue(pbi, :tracker => false, :truncate => 150, :class => "warning") %>
      </div>
      <%= render :partial => "post_its/sprint_board/custom_fields", :formats => [:html],
                 :locals => {:project => project, :issue => pbi} %>
      <div class="doers-reviewers-post-its-container">
        <%- if pbi.scrum_blocked? -%>
          <div class="<%= Issue.blocked_post_it_css_class %>">
            <%= l :label_blocked %>
          </div>
        <%- end -%>
      </div>
    </td>
  </tr>
  <tr>
    <td class="estimation">
      <%- if pbi.has_story_points? -%>
        <%= render :partial => "common/scrum_story_points", :formats => [:html],
                   :locals => {:project => project, :pbi => pbi, :read_only => read_only} %>
      <%- end -%>
    </td>
    <td class="spent">
      <%- if User.current.allowed_to?(:view_time_entries, project) -%>
        <%= render_hours(pbi.total_time, :title => l(:label_total_effort), :ignore_zero => true) %>
      <%- end -%>
    </td>
    <td class="pending">
      <%= render_hours(pbi.pending_effort, :title => l(:field_pending_effort), :ignore_zero => true) %>
    </td>
  </tr>
</table>

plugins/scrum/app/views/post_its/sprint_board/_pbi_row.html.erb
<%- pbi_row_id = "pbi_#{pbi.id}_row" -%>
<tr class="sprint-board post-it-vertical-move-cursor" id="<%= pbi_row_id %>">
  <td class="sprint-board">
    <%= render :partial => 'post_its/sprint_board/pbi', :formats => [:html],
               :locals => {:project => project, :pbi => pbi, :read_only => false} %>
  </td>
  <%- tasks = pbi.tasks_by_status_id
      task_statuses.each do |status| -%>
    <%- pbi_status_id = "pbi_#{pbi.id}_status_#{status.id}"
        other_pbi_status_ids = task_statuses.select{|other| other != status}.collect{
          |other| "pbi_#{pbi.id}_status_#{other.id}"
        } -%>
    <td id="<%= pbi_status_id %>" class="sprint-board">
      <%- tasks[status.id].each do |task| -%>
        <%= render :partial => 'post_its/sprint_board/task', :formats => [:html],
                   :locals => {:project => project,
                               :task => task,
                               :pbi_status_id => pbi_status_id,
                               :other_pbi_status_ids => other_pbi_status_ids,
                               :read_only => false} %>
      <%- end -%>
    </td>
    <%= render :partial => 'post_its/sprint_board/pbi_status', :formats => [:js],
               :locals => {:project => project,
                           :pbi_id => pbi.id,
                           :pbi_status_id => pbi_status_id,
                           :status => status} %>
  <%- end -%>
</tr>
<%= render :partial => 'post_its/sprint_board/pbi_row', :formats => [:js],
           :locals => {:project => project,
                       :pbi => pbi,
                       :pbi_row_id => pbi_row_id} %>

plugins/scrum/app/views/post_its/sprint_board/_pbi_row.js.erb
<%- if User.current.allowed_to?(:sort_sprint_board, project) and pbi.editable? -%>
  <%= javascript_tag do %>
    draggableOnTouchScreen("<%= pbi_row_id %>");
  <% end %>
<%- end -%>

plugins/scrum/app/views/post_its/sprint_board/_pbi_status.js.erb
<%= javascript_tag do %>
	$(document).ready(function() {
		$("#<%= pbi_status_id %>").droppable({
			accept: ".sprint-task",
			drop: function(event, ui) {
				if ($.isFunction($.fn.setupAjaxIndicator)) {
					setupAjaxIndicator();
				}
				if (!(ui.draggable.is($(this).children()))) {
					$.ajax({
						url: "<%= project_sprints_change_task_status_path(@project) %>",
						type: "POST",
						data: {task: encodeURIComponent($(ui.draggable).attr("id")),
									 status: encodeURIComponent("<%= status.id %>")},
						error: function() {
							alert("<%= l(:error_changing_task_status) %>");
							var task = $(ui.draggable);
							task.detach();
							task.appendTo($("#<%= "pbi_#{pbi_id}_status_" %>" + ui.draggable.attr("old-status")));
						},
						complete: function() {
							if ($.isFunction($.fn.hideOnLoad)) {
								hideOnLoad();
							}

						},
						success: function(response) {
							ui.draggable.attr("old-status", "<%= status.id %>");
							window["container_" + $(ui.draggable).attr("id")] = "";
							var draggableItem = $(ui.draggable), draggableItemId = draggableItem.attr('id').split('_')[1],
									taskIdLinkContent = '#' + draggableItemId, taskIdLink = $('a:contains(' + taskIdLinkContent + ')'),
									finalStatuses = ['closed', 'rejected'];
							finalStatuses.indexOf(response['new_status']) >= 0 ? taskIdLink.addClass('closed') : taskIdLink.removeClass('closed');
							$('#pending_effort_' + draggableItemId).val(response['new_pending_effort']);
						}
					});
				}
				ui.draggable.appendTo($(this)).removeAttr("style");
				ui.draggable.attr("style", "position: relative; " + ui.draggable.attr("style"));
			}
		});
	});
<% end %>

plugins/scrum/app/views/post_its/sprint_board/_task.html.erb
<%- task_id = "task_#{task.id}" -%>
<table id="<%= task_id %>" class="<%= task.post_it_css_class(:rotate => true, :scale => true, :draggable => true) %>"
       old-status="<%= task.status.id %>">
  <tr>
    <td class="content" colspan="3">
      <div class="content">
        <%- if User.current.allowed_to?(:edit_sprint_board, project) and 
               User.current.allowed_to?(:edit_issues, project) and
               task.editable? and !read_only -%>
          <%= link_to "", edit_task_path(task), :remote => true, :method => "GET",
                      :class => "icon icon-edit float-icon", :title => l(:label_edit_task) %>
        <%- end -%>
        <%- if User.current.allowed_to?(:log_time, project) -%>
            <%= link_to "", new_scrum_time_entry_path(task,
                                                      :pbi_status_id => pbi_status_id,
                                                      :other_pbi_status_ids => other_pbi_status_ids.join(","),
                                                      :task_id => task_id),
                        :remote => true, :method => "GET", :class => "icon icon-log-time float-icon",
                        :title => l(:button_log_time) %>
        <%- end -%>
        <%= render_issue_icons(task) %>
        <%= render :partial => "post_its/sprint_board/fields", :formats => [:html],
                   :locals => {:project => project, :issue => task} %>
        <div>
          <%= link_to_issue(task, :tracker => false, :truncate => 100) %>
        </div>
        <%= render :partial => "post_its/sprint_board/custom_fields", :formats => [:html],
                   :locals => {:project => project, :issue => task} %>
        <div class="doers-reviewers-post-its-container">
          <%- unless task.assigned_to.nil? -%>
            <div class="<%= Issue.assignor_post_it_css_class %>">
              <%= avatar(task.assigned_to, :size => "14") %> <%= link_to_user task.assigned_to %>
            </div>
          <%- end -%>
          <%- task.doers.first(1).each do |doer| -%>
            <div class="<%= Issue.doer_post_it_css_class %>">
              <%= avatar(doer, :size => "14") %> <%= link_to_user doer %>
            </div>
          <%- end -%>
          <%- task.reviewers.first(2).each do |reviewer| -%>
            <div class="<%= Issue.reviewer_post_it_css_class %>">
              <%= avatar(reviewer, :size => "14") %> <%= link_to_user reviewer %>
            </div>
          <%- end -%>
          <%- if task.scrum_blocked? -%>
            <div class="<%= Issue.blocked_post_it_css_class %>">
              <%= l :label_blocked %>
            </div>
          <%- end -%>
        </div>
      </div>
    </td>
  </tr>
  <tr>
    <td class="estimation">
      <%= render_hours(task.estimated_hours, :title => l(:field_estimated_hours)) %>
    </td>
    <td class="spent">
      <%- if User.current.allowed_to?(:view_time_entries, project) -%>
        <%= render_hours(task.spent_hours, :title => l(:label_spent_time), :ignore_zero => true,
                         :link => respond_to?(:issue_time_entries_path) ?
                                  issue_time_entries_path(task) :
                                  project_issue_time_entries_path(project, task)) %>
      <%- end -%>
    </td>
    <td class="pending">
      <%= render :partial => "common/scrum_pending_effort", :formats => [:html],
                 :locals => {:project => project, :task => task} %>
    </td>
  </tr>
</table>

<%= render :partial => "post_its/sprint_board/task", :formats => [:js],
           :locals => {:project => project,
                       :other_pbi_status_ids => other_pbi_status_ids,
                       :task_id => task_id,
                       :task => task} %>

plugins/scrum/app/views/post_its/sprint_board/_task.js.erb
<%- if User.current.allowed_to?(:edit_sprint_board, project) and task.editable? -%>
	<%= javascript_tag do %>
		<%- other_pbi_status_ids.each do |pbi_status_id| -%>
			$(document).ready(function() {
				$("#<%= task_id %>").draggable({
					revert: "invalid",
					axis: "x",
					containment: "<%= pbi_status_id %>",
					cursor: "ew-resize",
					stack: "table"
				});
				draggableOnTouchScreen("<%= task_id %>");
			});
		<%- end -%>
	<% end %>
<%- end -%>